application: izobitelno
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: app/js

- url: /css
  static_dir: app/css

- url: /images
  static_dir: app/images

- url: /fonts
  static_dir: app/fonts

- url: /_ah/spi/.*
  script: main.application_API

- url: /orgs/new
  script: main.app
#  login: required

- url: /edit_org/(.*)
  script: main.app
#  login: required

- url: .*
  script: main.app
#  login: required


libraries:
- name: jinja2
  version: latest
- name: endpoints
  version: latest